kernelci.org: Add documentation for the CIP instance
kernelci/kernelci-project pull request #127
Opened 2022-09-20 14:34 UTC by patersonc

Add documentation for the CIP instance

2022-09-20 14:34 UTC, patersonc commented
Hi @aliceinwire 

Do you have any other topics you'd like added?

Thanks, Chris

2022-09-21 13:02 UTC, aliceinwire commented
@patersonc looks great for me!

2022-09-21 13:04 UTC, aliceinwire approved these changes

2022-09-21 13:06 UTC, aliceinwire requested changes

2022-09-21 13:06 UTC, aliceinwire commented on kernelci.org/content/en/docs/instances/cip.md
> +The test configurations (devices, test cases, rootfs etc.) are defind in
defind -> defined

2022-09-22 08:55 UTC, patersonc commented on kernelci.org/content/en/docs/instances/cip.md
> +The test configurations (devices, test cases, rootfs etc.) are defind in
oops! Fixed now

2022-09-22 08:59 UTC, merged