Docs: add section for lava-docker
kernelci/kernelci-project pull request #21
Opened 2021-07-09 18:07 UTC by aliceinwire

Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

2021-07-19 05:27 UTC, aliceinwire commented
Fixed commit title

2021-07-19 17:41 UTC, gctucker reviewed
`lava-docker` is a GitHub repository, so it's more a piece of software than a service.  As such I believe it should be moved under the "software maintainers" section rather than services.

2021-07-20 17:09 UTC, aliceinwire commented
> `lava-docker` is a GitHub repository, so it's more a piece of software than a service. As such I believe it should be moved under the "software maintainers" section rather than services.

@gctucker fixed

2021-07-20 17:54 UTC, gctucker approved these changes

2021-07-20 17:56 UTC, gctucker commented
Tested OK on staging https://static.staging.kernelci.org/docs/team/tsc/#lava-docker

2021-07-20 17:57 UTC, gctucker requested changes
Just saw a couple of minor things to tweak

2021-07-20 17:57 UTC, gctucker commented on kernelci.org/content/en/docs/team/tsc.md
> +* Repository: [`kernelci-core`](https://github.com/kernelci/lava-docker)
```suggestion
* Repository: [`lava-docker`](https://github.com/kernelci/lava-docker)
```

2021-07-20 17:57 UTC, gctucker commented on kernelci.org/content/en/docs/team/tsc.md
> +* Maintainer: `alicef`, `montjoie`
```suggestion
* Maintainers: `alicef`, `montjoie`
```

2021-07-20 18:00 UTC, aliceinwire commented
> Just saw a couple of minor things to tweak

fixed thanks

2021-07-20 20:52 UTC, gctucker approved these changes
Thanks, checked OK again on staging.

2021-07-20 20:52 UTC, merged