legacy: chromeos: add R118 changelog
kernelci/kernelci-project pull request #269
Opened 2023-11-09 15:04 UTC by 10ne1

ChromeOS testing on KernelCI is now happening using the latest LTS release R118.

Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>

2023-11-17 16:20 UTC, a-wai requested changes

2023-11-17 16:20 UTC, a-wai commented on kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
This should be `R118` (see line above as GH doesn't allow me to comment directly on it)

2023-11-17 16:20 UTC, a-wai commented on kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
> +- Droppped the chromeos-kernel-5_10 bump in favor of the 5.10 shipped in R118
```suggestion
- Dropped the chromeos-kernel-5_10 bump in favor of the 5.10 shipped in R118
```

Typo.

Also, this doesn't sound clear to me, do you mean "dropped the bump to make chromeos-kernel-5_10 use our own forked 5.10" or something similar?

2023-11-17 16:20 UTC, a-wai commented on kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
> +- Masked newer chromeos-chrome ebuild version which doesn't have a binpkg, to avoid unnecessary long build times.
```suggestion
- Masked newer chromeos-chrome ebuild version which doesn't have a binpkg, to avoid unnecessarily long build times.
```

Nitpick

2023-11-20 12:48 UTC, a-wai commented
LGTM

2023-11-27 09:55 UTC, gctucker commented
Have you checked it looked as expected on the staging website?
https://static.staging.kernelci.org/docs/legacy/instances/chromeos/chromeos_changelog/

2023-11-27 12:31 UTC, gctucker commented
Thanks, will take a look next.  Also please note that it's a bit better to start the commit summary with `kernelci.org:` as the `kernelci-project` repository is not only for the static website but all the "admin" parts.

2023-11-27 12:31 UTC, merged