kernelci.org: add Advisory Board role definitions
kernelci/kernelci-project pull request #293
Opened 2023-12-12 11:36 UTC by gctucker

Add a section on the Advisory Board page with definitions for the key roles (Chair, Treasurer, PM).  Also update the wording in the intro paragraph accordingly.

2023-12-12 12:38 UTC, patersonc requested changes
Thank you @gctucker

2023-12-12 12:38 UTC, patersonc commented on kernelci.org/content/en/docs/org/board.md
> +help coordinate activites with the TSC, working groups and the wider team.
```suggestion
help coordinate activities with the TSC, working groups and the wider team.
```

2023-12-12 12:38 UTC, patersonc commented on kernelci.org/content/en/docs/org/board.md
> +take initiatives and help the project strive.
```suggestion
take initiatives and help the project thrive.
```

2023-12-15 15:07 UTC, patersonc commented on kernelci.org/content/en/docs/org/board.md
> +agreed on the following responsibilities:
```suggestion
agree on the following responsibilities:
```

2023-12-15 15:07 UTC, patersonc commented
Other than the small correction above, this MR looks okay to me.

2023-12-15 16:50 UTC, gctucker commented
Thanks for the review, I've applied your typo fix.

2023-12-15 21:40 UTC, patersonc approved these changes

2023-12-18 07:47 UTC, merged