_index: Update docs frontpage with kci-dev
kernelci/kernelci-project pull request #495
Opened 2024-11-26 12:24 UTC by aliceinwire

2024-11-26 12:24 UTC, aliceinwire commented
/staging

2024-11-26 15:57 UTC, patersonc requested changes
Thank you for the PR @aliceinwire !

2024-11-26 15:57 UTC, patersonc commented on kernelci.org/content/en/_index.md
> +  <p class="text-center">Start here if you want to interact with KernelCI instances</p>
Nit: We should add a full stop like the other bordered entries on this page.

Perhaps we could also make it clearer how the suggested interaction will happen? Maybe "programmatically"?
I'm open to better suggestions though!

```suggestion
  <p class="text-center">Start here if you want to interact with KernelCI instances programmatically.</p>
```

2024-11-28 08:00 UTC, patersonc approved these changes
LGTM. Thanks!

2024-11-28 08:56 UTC, nuclearcat commented
/staging

2024-12-12 13:38 UTC, aliceinwire commented
@nuclearcat can you merge this?

2024-12-12 16:33 UTC, merged